"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['cucmenterprise.py']
APP_NAME = "Update CUCM Enterprise"
DATA_FILES = [('', ['images']),('', ['schema']),('', ['db']),('', ['help'])]
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'app.icns',
    'plist': {
        'CFBundleGetInfoString': "Update CUCM Enterprise Parameters via AXL",
        'CFBundleIdentifier': "com.jeremy.osx.updatedn",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': "Copyright 2017, Jeremy Worden, All Rights Reserved"
    }
    }
    

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)